version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auditronai
    ports:
      - "127.0.0.1:8502:8501"  # Port Streamlit, limité à localhost
    volumes:
      - ./reports:/app/reports:rw
      - ./logs:/app/logs:rw
      - ./.cache:/app/.cache:rw
      - ./plugins:/app/plugins:rw
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-auditronai}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    security_opt:
      - no-new-privileges:true
    networks:
      - auditronai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:14-alpine
    container_name: auditronai-db
    environment:
      - POSTGRES_DB=${DB_NAME:-auditronai}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "127.0.0.1:5432:5432"  # Limité à localhost
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    security_opt:
      - no-new-privileges:true
    networks:
      - auditronai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: auditronai-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme}
    volumes:
      - redis_data:/data:rw
    ports:
      - "127.0.0.1:6379:6379"  # Limité à localhost
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    networks:
      - auditronai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: auditronai-postgres-data
  redis_data:
    name: auditronai-redis-data

networks:
  auditronai-network:
    name: auditronai-network
    driver: bridge
