name: auditronai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit>=1.24.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - psycopg2>=2.9.6
  - redis-py>=4.5.4
  - pydantic>=2.0.0
  - sqlalchemy>=2.0.0
  - alembic>=1.11.0
  - python-jose>=3.3.0
  - passlib>=1.7.4
  - python-multipart>=0.0.6
  - aiohttp>=3.8.4
  - asyncio>=3.4.3
  - uvicorn>=0.22.0
  - gunicorn>=20.1.0
  - bandit>=1.7.5
  - radon>=6.0.1
  - pylint>=2.17.4
  - mypy>=1.3.0
  - black>=23.3.0
  - isort>=5.12.0
  - pytest>=7.3.1
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.1.0
  - pytest-mock>=3.11.1
  - sphinx>=7.0.1
  - python-dotenv>=1.0.0
  - sentry-sdk>=1.28.1
  - prometheus-client>=0.17.0
  - boto3>=1.26.0
  - requests>=2.31.0
  - typing-extensions>=4.7.1
  - pyyaml>=6.0.1
  - pip
  - pip:
    - prospector>=1.10.2
    - vulture>=2.7
    - azure-storage-blob>=12.16.0
    - sphinx-rtd-theme>=1.2.1
