critique_n_refine:
  # Token management
  max_tokens: 100000  # Claude's token limit
  chunk_size: 8000    # Safe chunk size for processing
  
  # Optimization settings
  max_iterations: 3   # Maximum refinement iterations
  
  # Critique settings
  critique_aspects:
    - clarity
    - specificity
    - completeness
    - consistency
  
  # Improvement settings
  improvement_types:
    - structural
    - semantic
    - stylistic
    
  # Fallback settings
  fallback_strategies:
    - simplify_improvements
    - reduce_iterations
    - focus_critical_sections

  # Chunk processing
  chunk_overlap: 200  # Token overlap between chunks to maintain context
  min_chunk_size: 1000  # Minimum chunk size to maintain coherent analysis
  
  # Token budget allocation
  token_budget:
    prompt: 0.4      # 40% for prompt
    completion: 0.6   # 60% for completion/response
    
  # Performance optimization
  parallel_processing: false  # Process chunks sequentially for better control
  cache_results: true        # Cache intermediate results
  
  # Safety measures
  token_buffer: 1000         # Keep buffer for unexpected token usage
  max_improvement_size: 2000 # Maximum size of single improvement
