# Configuration de la base de données
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/auth_db"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DB = "auth_db"

# Configuration de l'authentification
SECRET_KEY = "your-secret-key-here"
AUTH_TOKEN_EXPIRE_MINUTES = 30
